import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const inputPath = join(root, "skills.json");
const outputPath = join(root, "src/generated/embedded_skills.ts");

const raw = readFileSync(inputPath, "utf-8");
const parsed = JSON.parse(raw) as unknown;

if (!Array.isArray(parsed) && (!parsed || typeof parsed !== "object")) {
  throw new Error("skills.json must be an array or object");
}

const banner = [
  "// This file is generated by scripts/generate-embedded-skills.ts",
  "// Do not edit manually.",
  "",
  "export const EMBEDDED_SKILLS_PAYLOAD = ",
].join("\n");

const content = `${banner}${JSON.stringify(parsed, null, 2)} as const;\n`;
writeFileSync(outputPath, content, "utf-8");
